### ISSUE TITLE
Create schematic sheet for LTC3 5 V DC-DC converter

### ISSUE THREAD

**Issue by nellump** [psas/launch-tower#20]
A placeholder sheet ("DC-DC Converter, 5V") already exists.  Drawing up the schematic should be reasonably straightforward.

We're using a Cincon EC4BU-12S05.  Refer to the design spec and data sheet for the particulars.  A custom component will likely need to be drawn to represent the converter.  The data sheet contains a table of pin assignments.

Please *do not* commit your work to the repo's "master" branch.  [Create a new branch.][1]  We can merge to "master" when you're finished.

[1]: http://www.sbf5.com/~cduan/technical/git/git-2.shtml

**Comment by austinjoseph** [comment]
USING TI PTN78020A

**Comment by austinjoseph** [comment]
Going to start working on this unless Roman comes back anytime soon!

**Comment by nellump** [comment]
DC-DC converter schematics are already completed.  I forgot to check the issues list to close off anything applicable.
