### ISSUE TITLE
Create schematic sheet for LTC3 19 V DC-DC converter

### ISSUE THREAD

**Issue by nellump** [psas/launch-tower#21]
A placeholder sheet ("DC-DC Converter, 19V") already exists. Drawing up the schematic should be reasonably straightforward.

We're using a nameless switching converter shipped direct From China, With Love. Datasheet? [Ha! Ha!][1] The [eBay auction page][2] makes the following claims:
   * Input voltage: 12V (10V-15V)
   * Output voltage: 19V
   * Output Current: 4A
   * Output power: 76W
   * Soft start time: 500mS
   * Over-current protection
   * Overheat protection
   * Short-circuit protection and automatic recovery
   * Full waterproof potting
   * Conversion efficiency: >85%
   * Load regulation: ± 2%
   * Voltage regulation: ±1%
   * Dynamic response speed: 5% 200uS
   * Module Properties: Non-isolated
   * working temperature: industrial grade(-20° C to 85° C)
   * Distance between mounting 2 holes:55mm
   * Diameter of mounting hole: 7mm
   * Size:68*58*25(mm)
   * Weight:160g

[1]: http://vignette3.wikia.nocookie.net/simpsons/images/e/e9/Nelson_Ha-Ha.jpg
[2]: http://www.ebay.com/itm/Waterproof-76W-DC-DC-Converter-DC-12V-to19V-4A-Boost-Step-up-Car-Power-Module-/271772377430

A custom component will likely need to be drawn to represent the converter. From the photos on the auction page, it appears to be a four-terminal device (Vin, 2x ground, Vout).

Please *do not* commit your work to the repo's "master" branch.  [Create a new branch.][3]  We can merge to "master" when you're finished.

[3]: http://www.sbf5.com/~cduan/technical/git/git-2.shtml

**Comment by austinjoseph** [comment]
USING TI PTN78020H For high powered rail.
