### ISSUE TITLE
Make BQ77PL900 footprint and schematic symbol in KiCAD

### ISSUE THREAD

**Issue by OutboundFlight** [psas/launch-tower#24]

**Comment by austinjoseph** [comment]
Component and Module Finished 30 May.

**Comment by OutboundFlight** [comment]
We need to vet this footprint against a known-good footrprint for this chip. There's one in the Eagle TI library under "DL R-PDSO-G48."

**Comment by austinjoseph** [comment]
The newer build of kicad has a standard footprint for this chip.  The schematics are already in the repo.
