### ISSUE TITLE
Make PTN708020 footprint and schematic symbol in KiCAD

### ISSUE THREAD

**Issue by OutboundFlight** [psas/launch-tower#25]
Double check if there are any pinout differences between the low- and high-powers versions.

**Comment by nellump** [comment]
I've already got a component (schematic symbol) created for the PTN78020W, saved to the LTC3_components.lib library.  It can be copied to create the PTN78020H.  Pretty sure their pin-outs are identical, but do verify.

**Comment by OutboundFlight** [comment]
Okay! I didn't catch that. I'll check the pinouts  tonight and then close
the issue.

**Comment by OutboundFlight** [comment]
Pinouts for both the high- and low-power version are identical. Closed.
