### ISSUE TITLE
BEAGLEBONE BLACK WITH WL1835 CAPE RUNNING FREERTOS

### ISSUE THREAD

**Issue by vinayashreeks** [psas/launch-tower#30]
Hi , i am a newbie with beaglebone black.I have installed freertos(V7.0.1) on beagle bone black using [https://github.com/guileschool/BEAGLEBONE-tutorials](url) .
Now i want to use wilink wl1835 cape with beagle bone black running freertos.
I am not getting any reference regarding this.
I want to know step by step procedure for this .
Can anyone provide any links or videos to integrate this cape on board and test whether sdio integration is working properly in this????
@vosechu @donpdonp @fitzgen @aperiodic @BartMassey @guileschool @beagleboneblack @freertos @WL1835 @OutboundFlight @TI @nellump

**Comment by andrewgreenberg** [comment]
Hi Vinayashreeks,
We don't use freertos on the BBB, and we don't use the wilink cape, so no, we can't help you. Good luck!
