### ISSUE TITLE
Beaglebone black UART0 pin details on p8 and p9 header

### ISSUE THREAD

**Issue by vinayashreeks** [psas/launch-tower#31]
hi 
I am using beaglebone black ,but due to some reasons i am not able to use 6 pin header for serial debug.May i know which pins in p8 and p9 headers corresponds to uart0_tx and uart0_rx.please help me,i know other uarts pin details ,but only uart0 i need.
@vosechu @donpdonp @fitzgen @aperiodic @BartMassey @beagleboneblack @ti @uart @andrewgreenberg @guileschool

**Comment by andrewgreenberg** [comment]
Hi vinayashreeks, why in the world are you asking us these questions in the PSAS launch-tower  repository. Please use the issues ONLY for issues regarding the PSAS launch-tower, and NOT for random questions that you have. Please go find an appropriate BeagleBone forum.
