### ISSUE TITLE
Investigate Intel Edison as a board

### ISSUE THREAD

**Issue by OutboundFlight** [psas/launch-tower#7]
Initially: the Edison is a lot smaller than the BBB, has very low power requirements, and is an x86 rather than ARM. On the other hand, there's very little support and we would need a separate analog input.

One thing that would help with this project is generating a list of what makes for a good LTC.

**Comment by nellump** [comment]
Edison looks like a nice board, and it might even be a better match for LTC3 if it wasn't for the lack of Ethernet.  That's a deal-breaker.  (Ethernet over USB is possible.  Not sure what that does to network latency.)

Expanding on aSmig's comparison above:
* Edison has a 500 MHz dual-core Atom proc.; BBB has a 1 GHz ARM A8 proc.
* Edison has 1 GB RAM; BBB has 512 MB.
* Both boards have 4 GB of eMMC.
* Edison has on-board WiFi and Bluetooth LE.
* Edison has no Ethernet.
* Edison compute module only supports 1.8 V IO.
* Both boards have more GPIOs than we'll know what to do with.
* Both boards can be easily mounted onto an appropriately-designed expansion board.
* Edison compute module is a tiny board with no external interfaces but a single Hirose connector.  It will require an expansion/breakout board to be useful.  In that respect, it is very similar to the Qseven boards.
* Edison has an on-board microcontroller external to the main processor.
* Prices appears to be about the same (~$55).

Reference:
* http://hackaday.com/2014/09/10/hands-on-with-the-intel-edison/
* http://www.mouser.com/new/Intel/intel-edison/
* http://www.amazon.com/dp/B00ND1KH10
* https://www.adafruit.com/products/2112

**Comment by BartMassey** [comment]
Ethernet over USB is fine for whatever we're going to be doing, IMHO. Nobody puts it in anymore because that.
